FROM python:3.7

# add project
#COPY ./code /app
#WORKDIR /app

# install flask
RUN pip install --upgrade pip
RUN pip install Flask==1.0.2 requests line-bot-sdk PyMYSQL

# run flask
#ENTRYPOINT ["python"]
#CMD ["test_flask.py"]

#RUN /bin/bash -c 'python test_flask.py'

# run flask
ENTRYPOINT ["python"]
#CMD ["app.py"]

